version: 1

update_configs:
  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/"
  
    allowed_updates:
      - match:
          update_type: "all"

    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    
    default_labels:
    - "dependencies"
    - "dependabot"

    default_reviewers:
    - "devotox"
